run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - sqlclosecheck
    - prealloc

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - (net/http.ResponseWriter).Write
      - (*encoding/json.Encoder).Encode
      - io.Copy
      - fmt.Fprintf
      - fmt.Fprintln
  
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too noisy for this project
      - shadow          # Too strict for existing codebase
  
  goimports:
    local-prefixes: github.com/johnrirwin/flyingforge
  
  misspell:
    locale: US

issues:
  exclude-rules:
    # Test files can have longer functions and unused params
    - path: _test\.go
      linters:
        - errcheck
        - unused
        - govet
    
    # Main can have unused results from signal handling
    - path: cmd/server/main\.go
      linters:
        - errcheck
    
    # HTTP handlers commonly ignore write errors
    - path: internal/httpapi/
      linters:
        - errcheck
    
    # Database layer has known patterns
    - path: internal/database/
      linters:
        - govet
    
    # MCP server has stdio patterns
    - path: internal/mcp/
      linters:
        - errcheck
  
  max-issues-per-linter: 50
  max-same-issues: 10
