run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - sqlclosecheck
    - rowserrcheck
    - exportloopref
    - errorlint
    - gosec
    - prealloc

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too noisy for this project
  
  goimports:
    local-prefixes: github.com/johnrirwin/rotorlife
  
  misspell:
    locale: US
  
  gosec:
    excludes:
      - G104  # Unhandled errors (covered by errcheck)
      - G304  # File path from variable (intentional in some cases)

issues:
  exclude-rules:
    # Test files can have longer functions and unused params
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    
    # Main can have unused results from signal handling
    - path: cmd/server/main\.go
      linters:
        - errcheck
  
  max-issues-per-linter: 50
  max-same-issues: 10
