version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - bodyclose
    - sqlclosecheck
    - prealloc
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - (net/http.ResponseWriter).Write
        - (*encoding/json.Encoder).Encode
        - io.Copy
        - fmt.Fprintf
        - fmt.Fprintln
        - (*database/sql.Rows).Close
        - (*io.ReadCloser).Close
        - (io.ReadCloser).Close
        - (*net/http.Response).Body.Close
    
    govet:
      enable-all: true
      disable:
        - fieldalignment  # Too noisy for this project
        - shadow          # Too strict for existing codebase
    
    misspell:
      locale: US
  exclusions:
    rules:
      # Test files can have longer functions and unused params
      - path: _test\.go
        linters:
          - errcheck
          - unused
          - govet
          - prealloc
      
      # Test utilities can have unchecked errors  
      - path: internal/testutil/
        linters:
          - errcheck
      
      # Main can have unused results from signal handling
      - path: cmd/server/main\.go
        linters:
          - errcheck
      
      # HTTP handlers commonly ignore write errors
      - path: internal/httpapi/
        linters:
          - errcheck
      
      # Database layer has known patterns
      - path: internal/database/
        linters:
          - govet
          - errcheck
      
      # MCP server has stdio patterns
      - path: internal/mcp/
        linters:
          - errcheck
          - prealloc
      
      # Auth service has cleanup patterns
      - path: internal/auth/
        linters:
          - errcheck
      
      # Radio service has file cleanup patterns
      - path: internal/radio/
        linters:
          - errcheck

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
